### ISSUE TITLE
Cannot seem to install

### ISSUE THREAD

**Issue by fabulousrice** [egtwobits/mesh_mesh_align_plus#11]
I select "Install from File" then the zipped file - but I do not see the add-on in the list of installed add-ons. A search with "Align" returns 0 results

**Comment by egtwobits** [comment]
You cannot use the zip file from the green "clone or download" button on the main page, you have to use one of the files attached to the bottom of a release on the [releases page](https://github.com/egtwobits/mesh_mesh_align_plus/releases), read the [installation instructions page](https://github.com/egtwobits/mesh_mesh_align_plus/wiki/Installation) if you need more info. Let me know how it goes.

**Comment by egtwobits** [comment]
Any news?
