### ISSUE TITLE
Can't align empty objects

### ISSUE THREAD

**Issue by eobet** [egtwobits/mesh_mesh_align_plus#12]
I have an empty with a lot of child objects, and I want to align the geometry of those child objects to some other geometry by means of only moving the parent empty.

That unfortunately doesn't work, since even if I manually grab a source and destination point, I get the error "cannot transform non-mesh or no active object".

Source and destination transforms should be able to be applied as relative deltas(?) to even empties.

**Comment by egtwobits** [comment]
Thanks for providing a useful example case for this! This feature will be in the next 0.6 release (applying transforms to non-mesh targets). Keep in mind that you will have to “Apply to: Object” though, as it doesn’t make sense to “Apply to: Mesh” for non-mesh objects :)
