### ISSUE TITLE
2.9 support

### ISSUE THREAD

**Issue by Tymski** [egtwobits/mesh_mesh_align_plus#16]
Does this work for 2.9?
How to install for 2.9?

**Comment by egtwobits** [comment]
Please don't use the green download button, read the instructions here: https://github.com/egtwobits/mesh_mesh_align_plus/wiki/Installation

**Comment by Tymski** [comment]
This is a weird folder structure, other blender addons on github can be installed with repo zip or have installation instructions in the readme

**Comment by egtwobits** [comment]
When I first ported my addon (before 2.8 beta was released), I tried to get the repo zip to work with multiple different structures but it wasn't supported at the time. Can you link me to a project that currently works that way via the Blender zip addon install process? Putting the install instructions on the home page is a good idea, I'll do that for next release perhaps.

**Comment by egtwobits** [comment]
For future reference, I'm only planning to support the latest version of blender.
