### ISSUE TITLE
Too much operators

### ISSUE THREAD

**Issue by hitrpr** [egtwobits/mesh_mesh_align_plus#18]
It is more about design.
Addon creates a lot of operators (also hidden and nondescribed). 
Looks like bad design.

![изображение](https://user-images.githubusercontent.com/21099918/99764409-06e2de80-2b0e-11eb-9158-746f0f3a3b35.png)
Is it possible to create less operators with options/adjustments?

**Comment by egtwobits** [comment]
This is not on my roadmap, there are other priorities to tend to (this would also be a big effort for not much gain).
