### ISSUE TITLE
contact?

### ISSUE THREAD

**Issue by SuddenDevelopment** [egtwobits/mesh_mesh_align_plus#21]
hi, I'm trying to write a new addon of my own, I've done a couple scripts and have some idea of what to do but would love to have someone I can ask that has the knowledge already to point me in the right direction. base don this plugin you definitely qualify... please shoot my an email if you don't mind: anthyony.aragues@gmail.com

**Comment by egtwobits** [comment]
Send me an email to egtwobits [at] gmail [dot] com.
