### ISSUE TITLE
Support for blender 3.1

### ISSUE THREAD

**Issue by JordanKlaers** [egtwobits/mesh_mesh_align_plus#24]
Just curious if this will be updated to work in blender 3.1

**Comment by egtwobits** [comment]
Closing this soon if no response. The forum bug discussed was an intermittent issue with align planes, which will be solved in an upcoming release (0.7.0). Let me know if you have more info if you still have questions.

**Comment by egtwobits** [comment]
This has been tested on 3.1, and 2.82 recently, so open a new issue if you still have problems.
