### ISSUE TITLE
The tab name is too long

### ISSUE THREAD

**Issue by Almaz** [egtwobits/mesh_mesh_align_plus#25]
Due to the limited space in the N-Panel and the large number of other useful addons, it is worth shortening the tab name to "Align".

**Comment by rust2** [comment]
Or, if it's possible, make it editable from Preferences->Addons and so Blender will load changed variant on startup

**Comment by egtwobits** [comment]
This has been merged (tab name is align), for release into the next version, which should be out very soon 👍

**Comment by ericsnekbytes** [comment]
Tab name has been shortened to "Align" with the just released v1.0, this has been resolved! Happy aligning :)
