### ISSUE TITLE
Only release version 0.7 available on Github

### ISSUE THREAD

**Issue by gdconnected** [egtwobits/mesh_mesh_align_plus#26]
All correspondence which I have read indicate the latest version (with easy-mode) being version 1.0 however 0.7 is the current latest release on Github

**Comment by egtwobits** [comment]
Version 1.0 is imminent, but not yet released. I updated all the documentation first, hang on for a bit and it will be out.

**Comment by ericsnekbytes** [comment]
Version 1.0 is out and this is now resolved! Sorry it took so long :)

**Comment by ericsnekbytes** [comment]
Closing!
