### ISSUE TITLE
Is the release v0.5.0 not compatible in 2.79b?

### ISSUE THREAD

**Issue by yassir-a-p** [egtwobits/mesh_mesh_align_plus#3]
Here is the console error that shows when I tried to install the 0.5.0 release on 2.79b windows 64bit version:
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Crows\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mesh_mesh_align_plus\__init__.py", line 25, in <module>
    import mesh_mesh_align_plus.utils.system as maplus_sys
  File "C:\Users\Crows\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\mesh_mesh_align_plus\utils\system.py", line 6, in <module>
    import mesh_mesh_align_plus.advanced_tools as maplus_adv_tools
AttributeError: module 'mesh_mesh_align_plus' has no attribute 'advanced_tools'
```

Is the 0.5.0 release intended only for 2.8 or it is just a bug? Because I read the release note and that it has an update for 2.8, thus implies that it is also for earlier version of Blender.

**Comment by schroef** [comment]
Indeed, this addon is coded for 2.80
I would need a some additional functions so it is compatible with both versions or it should have 2 repos. I do believe there is a version for 2.79

Let me check that

**Comment by schroef** [comment]
Okay it did, if you check the master and eather check the "Master" dropdown, check for tags [v0.0.4](https://github.com/egtwobits/mesh_mesh_align_plus/tree/v0.4.0) or check under releases. I do believe the older version has different functionality or working methods.  You would need to check that

**Comment by egtwobits** [comment]
Mesh Align Plus v0.5.0 or later only supports Blender 2.8x, earlier versions (v0.4.0 or earlier) can be run in 2.7x.

**Comment by yassir-a-p** [comment]
Thanks for the confirmation. I don't expect you to support earlier versions. I just suggest that you state it clearly that 0.5 (and forward?) are only compatible for 2.8x in the release section. Because currently the wording says "Mesh Align Plus has been updated for Blender 2.80..." and for me that implies that it is compatible with both 2.7x and 2.8.
Or maybe it's just me.
