### ISSUE TITLE
Not aligning

### ISSUE THREAD

**Issue by OldGeek1970** [egtwobits/mesh_mesh_align_plus#30]
Why are my objects not mating in any logical way?

**Comment by ericsnekbytes** [comment]
What are you trying to do? Mating can be a pretty simple task depending on your problem. Have you seen [the wiki](https://github.com/egtwobits/mesh_mesh_align_plus/wiki)? There's GIFs of just about everything there and detailed explainers of all the tools.

**Comment by OldGeek1970** [comment]
I got the simple face mate to work. 👍🏼
That's what I really needed.  The tutorials were not very helpful. Tha KS,
John

[ Apologies for spelling or grammar errors.  Chances are I am dictating to
the phone without my glasses. ]

**Comment by ericsnekbytes** [comment]
But like, wat? There are short video clips of almost everything. What were you struggling with?

**Comment by ericsnekbytes** [comment]
Would really appreciate your feedback here, I spent a lot of time on the wiki/instructions and accompanying GIFs.

**Comment by OldGeek1970** [comment]
Sorry.  I guess it's just not easy or intuitive.  I will try to look at it
again sometime. ~J

[ Apologies for spelling or grammar errors.  Chances are I am dictating to
the phone without my glasses. ]
