### ISSUE TITLE
"Align Objects" make destination object change scale

### ISSUE THREAD

**Issue by PharahLong** [egtwobits/mesh_mesh_align_plus#31]
Reproduce the issue by creating a new 'Cube,' setting only the Z scale to (-1) so scale will be (1,1,-1). Then, create another 'Cube' and use the align tool (Align Object). After clicking the button, the source object aligns correctly, but it causes the destination object to change all scale values to (-1, -1, -1).

**Comment by ericsnekbytes** [comment]
@PharahLong I should probably make the warnings more prominent (they're in a few places now), but Mesh Align Plus, like many of Blender's own built-in tools, does not support non-uniform scaling.
