### ISSUE TITLE
Unable to enable addon in 2.80 beta

### ISSUE THREAD

**Issue by dabinn** [egtwobits/mesh_mesh_align_plus#5]
Installed the 0.5.0 release from zip, when clicked the enable checkbox, Blender showed error.
![image](https://user-images.githubusercontent.com/21699064/54709251-2464e580-4b80-11e9-89db-8bcc77eb7b09.png)

![image](https://user-images.githubusercontent.com/21699064/54709221-13b46f80-4b80-11e9-9954-a6773313757b.png)

**Comment by Derjyn** [comment]
Same here! Looking forward to this getting resolved :)

**Comment by Greyligth** [comment]
My first error was 

RNA Types object has not attribute view3d_mt_object_specials

There seems to be a change in the blender api.

I have removed the Addon, installed the Addon and changed \utils\system.py before the activation as follows:
change:
VIEW3D_MT_object_specials  to  VIEW3D_MT_object_context_menu
and
VIEW3D_MT_edit_mesh_specials  to  VIEW3D_MT_edit_mesh_context_menu

in the register and unregister method.

It then looks like:

def register():
    # Make custom classes available inside blender via bpy.types
    for cls in classes:
        bpy.utils.register_class(cls)

    # Extend the scene class here to include the addon data
    bpy.types.Scene.maplus_data = bpy.props.PointerProperty(
        type=maplus_storage.MAPlusData
    )

    bpy.types.VIEW3D_MT_object_context_menu.append(maplus_guitools.specials_menu_items)
    bpy.types.VIEW3D_MT_edit_mesh_context_menu.append(maplus_guitools.specials_menu_items)


def unregister():
    del bpy.types.Scene.maplus_data
    bpy.types.VIEW3D_MT_object_context_menu.remove(maplus_guitools.specials_menu_items)
    bpy.types.VIEW3D_MT_edit_mesh_context_menu.remove(maplus_guitools.specials_menu_items)

    # Remove custom classes from blender's bpy.types
    for cls in reversed(classes):
        bpy.utils.unregister_class(cls)

**Comment by casterle** [comment]
I'm getting the same error as the OP.

**Comment by zmp2000** [comment]
Same error here! Waiting for an update!

**Comment by cogitas3d** [comment]
I have the same error with output:

> Exception in module register(): /home/linux3dcs/.config/blender/2.80/scripts/addons/mesh_mesh_align_plus/__init__.py
> Traceback (most recent call last):
>   File "/home/linux3dcs/Programs/OrtogOnBlender/Blender280/2.80/scripts/modules/addon_utils.py", line 384, in enable
>     mod.register()
>   File "/home/linux3dcs/.config/blender/2.80/scripts/addons/mesh_mesh_align_plus/utils/system.py", line 563, in register
>     bpy.types.VIEW3D_MT_object_specials.append(maplus_guitools.specials_menu_items)
> AttributeError: 'RNA_Types' object has no attribute 'VIEW3D_MT_object_specials'
> 
> Exception in module register(): /home/linux3dcs/.config/blender/2.80/scripts/addons/mesh_mesh_align_plus/__init__.py
> Traceback (most recent call last):
>   File "/home/linux3dcs/Programs/OrtogOnBlender/Blender280/2.80/scripts/modules/addon_utils.py", line 384, in enable
>     mod.register()
>   File "/home/linux3dcs/.config/blender/2.80/scripts/addons/mesh_mesh_align_plus/utils/system.py", line 556, in register
>     bpy.utils.register_class(cls)
> ValueError: register_class(...): already registered as a subclass

**Comment by cogitas3d** [comment]
@cufor it works perfectly! Thank you!

**Comment by casterle** [comment]
@cufor Thank you, addon activates correctly now. I've attached an updated zip file contained the patched file.
[mesh_mesh_align_plus.zip](https://github.com/egtwobits/mesh_mesh_align_plus/files/3123469/mesh_mesh_align_plus.zip)

**Comment by cufor** [comment]
You are welcome. @casterle Thanks for the zip

**Comment by egtwobits** [comment]
@cufor Thanks for that info! It saved a huge amount of time I would have spent tracking down that API change.

Side question: does anyone here use the advanced tools, or only the quick tools in the N panel? Adv. tools aren't even documented anymore because they've pretty much been superseded by the quick tools.

There's been a lot of activity on this issue, I'll try to be quicker with a fix next time an issue like this pops up. Thanks for being active on MAPlus everyone! Official update release should be out soon :)

**Comment by cufor** [comment]
@egtobits Thank you for the time to create this very useful 'little' Tool. It saved me a lot of time :)
Side answer: There are advanced tools? So - no - never used them.

**Comment by egtwobits** [comment]
Thanks everyone! Closing this one out.

**Comment by DeadKiller981** [comment]
@egtwobits I don't understand what @cufor did to fix the issue. And when I unzipped your file inside the Graswald file. The error disappeared but I still can't see it in the tools section. Please help.

**Comment by egtwobits** [comment]
@DeadKiller981 Cufor found a change in the Blender interface code that affects how specials/right click menu items are added (MAPlus uses some context menu shortcuts so when Blender made the change it originally broke the addon). I'm not sure what you mean by "Graswald file", maybe if you provide more info we can help you.

**Comment by Chokiz99** [comment]
Hi I think that cufor's answer might be the solution to my problem but I dont understand it at all someone can give me a better explaining?
