### ISSUE TITLE
Unable to install MAP 

### ISSUE THREAD

**Issue by raindropsfromsky** [egtwobits/mesh_mesh_align_plus#6]
I am using Blender 2.8 dated 22-5-2019, on Windows Home 64 bit.

I have used MAP in the past. Each time I download the latest zip from GitHub and then install it using the **Preferences** menu of Blender. After installing, I have to put a tick in the addon to activate it.

I use many other apps from GitHub using the same method. 

This week I installed MAP as usual, but I am unable to see it in the list. I tried searching for "mesh", "align" and "plus". But this addon is not found.

I am unable to see the addon in the **Tools** tab (where it used to appear earlier).
Blender shows me the other addons, such as Fast carve, measureIT, ArchiPack 2 PRO, Archimesh, Looptools, etc. but not the MAP.

**Comment by egtwobits** [comment]
The add-on is in the N panel now, since V0.5.0. I'm at work now, so if you still have problems we can take a look later :)

**Comment by raindropsfromsky** [comment]
yes, sorry. I should have said the N panel. 
That's where it used to be.
Now I cannot see it there, or even in the Addon list in the **Preferences** dialog.

**Comment by egtwobits** [comment]
Are you using the right zip file? The big green "clone or download" button will not work, it has to be the zip file posted at the bottom of the release for that version (on the releases page or at [the version page](https://github.com/egtwobits/mesh_mesh_align_plus/releases/tag/v0.5.2)).

**Comment by raindropsfromsky** [comment]
No I was downloading this zip file, by clicking on the **Clone or Download** green button first, and then  clicking on the **Download Zip** button, as shown below:

![image](https://user-images.githubusercontent.com/9047168/58532333-d8c75b80-8202-11e9-945f-c39b57439136.png)

**Branch:** Master

I am not a coder, so I did not know this access at all. Thanks for the clarification.
I will try this on my home PC and report.

**Comment by egtwobits** [comment]
BTW, there's a new version so grab that one (v0.5.3).

**Comment by raindropsfromsky** [comment]
Got the correct version, and it got installed.
